version: '2'
services:
 redis:
   image: redis
   ports:
     - "6379:6379"
   expose:
     - "6379"
 ether_bot:
   build: .
   security_opt:
     - seccomp:unconfined
   ports:
     - "8080:8080"
   expose:
     - "8080"
